### ISSUE TITLE
Panic negative WaitGroup counter in TestPeerConnection_Renegotiation_Trickle

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1299]
=== RUN   TestPeerConnection_Renegotiation_Trickle
```
panic: sync: negative WaitGroup counter

goroutine 4311 [running]:
sync.(*WaitGroup).Add(0xc000099800, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/sync/waitgroup.go:74 +0x2c0
sync.(*WaitGroup).Done(...)
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/sync/waitgroup.go:99
github.com/pion/webrtc/v3.TestPeerConnection_Renegotiation_Trickle.func2(0x0)
	/home/travis/gopath/src/github.com/pion/webrtc/peerconnection_renegotiation_test.go:568 +0x1a7
github.com/pion/webrtc/v3.(*ICEGatherer).Gather.func1(0x0, 0x0)
	/home/travis/gopath/src/github.com/pion/webrtc/icegatherer.go:166 +0x480
github.com/pion/ice/v2.(*Agent).gatherCandidates.func1(0xc00013ac80)
	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.3/gather.go:90 +0x136
created by github.com/pion/ice/v2.(*Agent).gatherCandidates
	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.3/gather.go:83 +0x110
FAIL	github.com/pion/webrtc/v3	51.701s
```

**Comment by at-wat** [comment]
This is caused by mixture of two candidate gathering routine.
https://github.com/pion/ice/issues/236
