### ISSUE TITLE
Timeout during TestICERestart on CI

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#1311]
```
=== RUN   TestICERestart
goroutine profile: total 29
2 @ 0x465540 0x433818 0x4335cb 0x9442a3 0x496481
#	0x9442a2	github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func1+0x82	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:395

2 @ 0x465540 0x45e30a 0x45d8d5 0x4d62e4 0x4d7788 0x4d774e 0x6b901a 0x6dc0ee 0x6d9f25 0x930bdc 0x496481
#	0x45d8d4	internal/poll.runtime_pollWait+0x54			/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/netpoll.go:203
#	0x4d62e3	internal/poll.(*pollDesc).wait+0xe3			/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_poll_runtime.go:87
#	0x4d7787	internal/poll.(*pollDesc).waitRead+0x227		/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
#	0x4d774d	internal/poll.(*FD).ReadFrom+0x1ed			/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_unix.go:219
#	0x6b9019	net.(*netFD).readFrom+0x79				/home/travis/.gimme/versions/go1.14.linux.amd64/src/net/fd_unix.go:208
#	0x6dc0ed	net.(*UDPConn).readFrom+0x8d				/home/travis/.gimme/versions/go1.14.linux.amd64/src/net/udpsock_posix.go:47
#	0x6d9f24	net.(*UDPConn).ReadFrom+0x94				/home/travis/.gimme/versions/go1.14.linux.amd64/src/net/udpsock.go:118
#	0x930bdb	github.com/pion/ice/v2.(*candidateBase).recvLoop+0x2cb	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:124

2 @ 0x465540 0x45e30a 0x45d8d5 0x4d62e4 0x4d8e1e 0x4d8de7 0x6d1cff 0x8e3092 0x8e9f71 0x8e9f32 0x8f1005 0x496481
#	0x45d8d4	internal/poll.runtime_pollWait+0x54			/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/netpoll.go:203
#	0x4d62e3	internal/poll.(*pollDesc).wait+0xe3			/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_poll_runtime.go:87
#	0x4d8e1d	internal/poll.(*pollDesc).waitRead+0x17d		/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
#	0x4d8de6	internal/poll.(*FD).RawRead+0x146			/home/travis/.gimme/versions/go1.14.linux.amd64/src/internal/poll/fd_unix.go:534
#	0x6d1cfe	net.(*rawConn).Read+0x6e				/home/travis/.gimme/versions/go1.14.linux.amd64/src/net/rawconn.go:43
#	0x8e3091	golang.org/x/net/internal/socket.(*Conn).recvMsg+0x3e1	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20200625001655-4c5254603344/internal/socket/rawconn_msg.go:32
#	0x8e9f70	golang.org/x/net/internal/socket.(*Conn).RecvMsg+0x210	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20200625001655-4c5254603344/internal/socket/socket.go:255
#	0x8e9f31	golang.org/x/net/ipv4.(*payloadHandler).ReadFrom+0x1d1	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20200625001655-4c5254603344/ipv4/payload_cmsg.go:31
#	0x8f1004	github.com/pion/mdns.(*Conn).start+0x174		/home/travis/gopath/pkg/mod/github.com/pion/mdns@v0.0.4/conn.go:256

2 @ 0x465540 0x476889 0x571a0f 0x496481
#	0x571a0e	context.propagateCancel.func1+0x10e	/home/travis/.gimme/versions/go1.14.linux.amd64/src/context/context.go:276

2 @ 0x465540 0x476889 0x820439 0x496481
#	0x820438	github.com/pion/dtls/v2/internal/net/connctx.(*connCtx).Read.func1+0x138	/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/internal/net/connctx/connctx.go:62

2 @ 0x465540 0x476889 0x82c464 0x93f93f 0x95720f 0x496481
#	0x82c463	github.com/pion/transport/packetio.(*Buffer).Read+0x223		/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.10.1/packetio/buffer.go:254
#	0x93f93e	github.com/pion/ice/v2.(*Conn).Read+0x10e			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/transport.go:75
#	0x95720e	github.com/pion/webrtc/v3/internal/mux.(*Mux).readLoop+0x1ce	/home/travis/gopath/src/github.com/pion/webrtc/internal/mux/mux.go:106

2 @ 0x465540 0x476889 0x82c464 0x955e5b 0x81fa85 0x86eca6 0x8a6904 0x496481
#	0x82c463	github.com/pion/transport/packetio.(*Buffer).Read+0x223			/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.10.1/packetio/buffer.go:254
#	0x955e5a	github.com/pion/webrtc/v3/internal/mux.(*Endpoint).Read+0x8a		/home/travis/gopath/src/github.com/pion/webrtc/internal/mux/endpoint.go:36
#	0x81fa84	github.com/pion/dtls/v2/internal/net/connctx.(*connCtx).Read+0x274	/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/internal/net/connctx/connctx.go:77
#	0x86eca5	github.com/pion/dtls/v2.(*Conn).readAndBuffer+0x175			/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:552
#	0x8a6903	github.com/pion/dtls/v2.(*Conn).handshake.func3+0x103			/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:826

2 @ 0x465540 0x476889 0x89d3bd 0x89c310 0x8a666a 0x496481
#	0x89d3bc	github.com/pion/dtls/v2.(*handshakeFSM).wait+0x26c	/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/handshaker.go:246
#	0x89c30f	github.com/pion/dtls/v2.(*handshakeFSM).Run+0x57f	/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/handshaker.go:158
#	0x8a6669	github.com/pion/dtls/v2.(*Conn).handshake.func2+0xe9	/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:807

2 @ 0x465540 0x476889 0x94442a 0x496481
#	0x944429	github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func2+0x159	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:404

1 @ 0x465540 0x433818 0x43358b 0x57f1b9 0x5855a7 0x57ea6c 0x581128 0x57f980 0xaf2148 0x465142 0x496481
#	0x57f1b8	testing.(*T).Run+0x698		/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1044
#	0x5855a6	testing.runTests.func1+0xa6	/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1285
#	0x57ea6b	testing.tRunner+0x1eb		/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:992
#	0x581127	testing.runTests+0x527		/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1283
#	0x57f97f	testing.(*M).Run+0x2ff		/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:1200
#	0xaf2147	main.main+0x347			_testmain.go:628
#	0x465141	runtime.main+0x211		/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/proc.go:203

1 @ 0x465540 0x433818 0x43358b 0x923e65 0x92e5ca 0xa41357 0xa4c04a 0xa8d012 0x57ea6c 0x496481
#	0x923e64	github.com/pion/ice/v2.(*Agent).run+0x1b4			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:176
#	0x92e5c9	github.com/pion/ice/v2.(*Agent).Restart+0x2c9			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:1153
#	0xa41356	github.com/pion/webrtc/v3.(*ICETransport).restart+0x276		/home/travis/gopath/src/github.com/pion/webrtc/icetransport.go:166
#	0xa4c049	github.com/pion/webrtc/v3.(*PeerConnection).CreateOffer+0xb59	/home/travis/gopath/src/github.com/pion/webrtc/peerconnection.go:404
#	0xa8d011	github.com/pion/webrtc/v3.TestICERestart+0x411			/home/travis/gopath/src/github.com/pion/webrtc/peerconnection_go_test.go:845
#	0x57ea6b	testing.tRunner+0x1eb						/home/travis/.gimme/versions/go1.14.linux.amd64/src/testing/testing.go:992

1 @ 0x465540 0x433818 0x43358b 0x931697 0x92a08b 0x946ce3 0x924046 0x496481
#	0x931696	github.com/pion/ice/v2.(*candidateBase).close+0xf6		/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:177
#	0x92a08a	github.com/pion/ice/v2.(*Agent).deleteAllCandidates+0x10a	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:887
#	0x946ce2	github.com/pion/ice/v2.(*Agent).Restart.func1+0x342		/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:1168
#	0x924045	github.com/pion/ice/v2.(*Agent).taskLoop+0x115			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:218

1 @ 0x465540 0x476889 0x8727ba 0x86a5ab 0x86b494 0x86b089 0xa37b2b 0xa57bb3 0xabacab 0xa47785 0x496481
#	0x8727b9	github.com/pion/dtls/v2.(*Conn).handshake+0x659					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:868
#	0x86a5aa	github.com/pion/dtls/v2.createConn+0x155a					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:194
#	0x86b493	github.com/pion/dtls/v2.ClientWithContext+0x103					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:251
#	0x86b088	github.com/pion/dtls/v2.Client+0xe8						/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:220
#	0xa37b2a	github.com/pion/webrtc/v3.(*DTLSTransport).Start+0x27a				/home/travis/gopath/src/github.com/pion/webrtc/dtlstransport.go:312
#	0xa57bb2	github.com/pion/webrtc/v3.(*PeerConnection).startTransports+0x3d2		/home/travis/gopath/src/github.com/pion/webrtc/peerconnection.go:1674
#	0xabacaa	github.com/pion/webrtc/v3.(*PeerConnection).SetRemoteDescription.func2+0x19a	/home/travis/gopath/src/github.com/pion/webrtc/peerconnection.go:869
#	0xa47784	github.com/pion/webrtc/v3.(*operations).start+0xd4				/home/travis/gopath/src/github.com/pion/webrtc/operations.go:77

1 @ 0x465540 0x476889 0x8727ba 0x86a5ab 0x86b674 0x86b1d9 0xa3816a 0xa57bb3 0xabacab 0xa47785 0x496481
#	0x8727b9	github.com/pion/dtls/v2.(*Conn).handshake+0x659					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:868
#	0x86a5aa	github.com/pion/dtls/v2.createConn+0x155a					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:194
#	0x86b673	github.com/pion/dtls/v2.ServerWithContext+0x103					/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:263
#	0x86b1d8	github.com/pion/dtls/v2.Server+0xe8						/home/travis/gopath/pkg/mod/github.com/pion/dtls/v2@v2.0.1/conn.go:230
#	0xa38169	github.com/pion/webrtc/v3.(*DTLSTransport).Start+0x8b9				/home/travis/gopath/src/github.com/pion/webrtc/dtlstransport.go:314
#	0xa57bb2	github.com/pion/webrtc/v3.(*PeerConnection).startTransports+0x3d2		/home/travis/gopath/src/github.com/pion/webrtc/peerconnection.go:1674
#	0xabacaa	github.com/pion/webrtc/v3.(*PeerConnection).SetRemoteDescription.func2+0x19a	/home/travis/gopath/src/github.com/pion/webrtc/peerconnection.go:869
#	0xa47784	github.com/pion/webrtc/v3.(*operations).start+0xd4				/home/travis/gopath/src/github.com/pion/webrtc/operations.go:77

1 @ 0x465540 0x476889 0x923e3a 0x92dd66 0x93130f 0x930b8e 0x496481
#	0x923e39	github.com/pion/ice/v2.(*Agent).run+0x189			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:172
#	0x92dd65	github.com/pion/ice/v2.(*Agent).validateNonSTUNTraffic+0x1c5	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:1078
#	0x93130e	github.com/pion/ice/v2.handleInboundCandidateMsg+0x6be		/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:154
#	0x930b8d	github.com/pion/ice/v2.(*candidateBase).recvLoop+0x27d		/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:129

1 @ 0x465540 0x476889 0x923e3a 0x93112b 0x930b8e 0x496481
#	0x923e39	github.com/pion/ice/v2.(*Agent).run+0x189		/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:172
#	0x93112a	github.com/pion/ice/v2.handleInboundCandidateMsg+0x4da	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:144
#	0x930b8d	github.com/pion/ice/v2.(*candidateBase).recvLoop+0x27d	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/candidate_base.go:129

1 @ 0x465540 0x476889 0x923e3a 0x945093 0x926ab6 0x496481
#	0x923e39	github.com/pion/ice/v2.(*Agent).run+0x189			/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:172
#	0x945092	github.com/pion/ice/v2.(*Agent).connectivityChecks.func1+0x142	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:471
#	0x926ab5	github.com/pion/ice/v2.(*Agent).connectivityChecks+0x385	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:526

1 @ 0x465540 0x476889 0x92417b 0x496481
#	0x92417a	github.com/pion/ice/v2.(*Agent).taskLoop+0x24a	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:214

1 @ 0x465540 0x476889 0x926a94 0x496481
#	0x926a93	github.com/pion/ice/v2.(*Agent).connectivityChecks+0x363	/home/travis/gopath/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.4/agent.go:521

1 @ 0x5f0343 0x5f010a 0x5ec24c 0xa2cc44 0x496481
#	0x5f0342	runtime/pprof.writeRuntimeProfile+0xa2			/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/pprof/pprof.go:694
#	0x5f0109	runtime/pprof.writeGoroutine+0xc9			/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/pprof/pprof.go:656
#	0x5ec24b	runtime/pprof.(*Profile).WriteTo+0x4fb			/home/travis/.gimme/versions/go1.14.linux.amd64/src/runtime/pprof/pprof.go:329
#	0xa2cc43	github.com/pion/transport/test.TimeOut.func1+0x93	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.10.1/test/util.go:18

panic: timeout

goroutine 2597 [running]:
github.com/pion/transport/test.TimeOut.func1()
	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.10.1/test/util.go:21 +0x160
created by time.goFunc
	/home/travis/.gimme/versions/go1.14.linux.amd64/src/time/sleep.go:168 +0x52
FAIL	github.com/pion/webrtc/v3	56.756s
```
https://travis-ci.org/github/pion/webrtc/jobs/707161211

**Comment by at-wat** [comment]
`candidateBase.conn` was `Close()`-ed but `recvLoop()` didn't stop.

**Comment by at-wat** [comment]
related?: https://github.com/golang/go/issues/25839

**Comment by tarrencev** [comment]
@at-wat did pion/ice#239 resolve this?

**Comment by Sean-Der** [comment]
Closed for https://github.com/pion/webrtc/issues/1466
