### ISSUE TITLE
pc.Close deadlocks under load

### ISSUE THREAD

**Issue by jech** [pion/webrtc#1459]
Using v3.0.0-beta.4.

We've just run a reasonably large conference using the Unnamed SFU, and the server deadlocked twice.  I managed to catch a trace, and it looks like a call to `pc.Close` failed to terminate:
```
goroutine 26654 [select, 2 minutes]:
github.com/pion/ice/v2.(*Agent).run(0xc0028d9340, 0x9bc400, 0xc0035da720, 0xc004da1410, 0x8afce0, 0x60)
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/agent.go:173 +0x145
github.com/pion/ice/v2.(*Conn).Write(0xc004718700, 0xc002228d80, 0x27, 0x30, 0x465800, 0xc001508f90, 0xc001508f98)
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/transport.go:93 +0x1fc
github.com/pion/webrtc/v3/internal/mux.(*Endpoint).Write(0xc000bf7020, 0xc002228d80, 0x27, 0x30, 0xc002833500, 0xc004da1400, 0xc00460e660)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/internal/mux/endpoint.go:41 +0x59
github.com/pion/dtls/v2/internal/net/connctx.(*connCtx).Write(0xc002833500, 0x9bbc80, 0xc0000b8020, 0xc002228d80, 0x27, 0x30, 0x0, 0x0, 0x0)
        /home/jch/go/pkg/mod/github.com/pion/dtls/v2@v2.0.2/internal/net/connctx/connctx.go:121 +0x1c5
github.com/pion/dtls/v2.(*Conn).writePackets(0xc0017d2000, 0x9bbc80, 0xc0000b8020, 0xc0015091a0, 0x1, 0x1, 0x0, 0x0)
        /home/jch/go/pkg/mod/github.com/pion/dtls/v2@v2.0.2/conn.go:396 +0x8c5
github.com/pion/dtls/v2.(*Conn).notify(0xc0017d2000, 0x9bbc80, 0xc0000b8020, 0xc001110001, 0xc0007802b8, 0xc005100540)
        /home/jch/go/pkg/mod/github.com/pion/dtls/v2@v2.0.2/conn.go:757 +0x1d5
github.com/pion/dtls/v2.(*Conn).close(0xc0017d2000, 0xc001509201, 0x6ec065, 0xc0052308a0)
        /home/jch/go/pkg/mod/github.com/pion/dtls/v2@v2.0.2/conn.go:899 +0x1db
github.com/pion/dtls/v2.(*Conn).Close(0xc0017d2000, 0x0, 0x0)
        /home/jch/go/pkg/mod/github.com/pion/dtls/v2@v2.0.2/conn.go:334 +0x30
github.com/pion/webrtc/v3.(*DTLSTransport).Stop(0xc000222a80, 0x0, 0x0)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/dtlstransport.go:393 +0x179
github.com/pion/webrtc/v3.(*PeerConnection).Close(0xc0024b64e0, 0xc003fff890, 0xc003aa0880)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/peerconnection.go:1749 +0x2b1
sfu/rtpconn.addDownConn(0xc000e95c80, 0xc003aa0880, 0x20, 0x9bc340, 0xc002306300, 0x0, 0x0, 0x0)
        /home/jch/go/src/sfu/rtpconn/webclient.go:297 +0x41e
```
I'm not familiar with this part of the code, but the following looks suspicious:
```
goroutine 42288 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc002aec3d8)
        /usr/lib/go-1.15/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc002aec3d0)
        /usr/lib/go-1.15/src/sync/waitgroup.go:130 +0x65
github.com/pion/ice/v2.(*Agent).gatherCandidates(0xc0028d9340, 0x9bbc40, 0xc004887440)
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/gather.go:118 +0x2c5
created by github.com/pion/ice/v2.(*Agent).GatherCandidates.func1
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/gather.go:74 +0x13e
```

```
goroutine 26830 [semacquire, 2 minutes]:
sync.runtime_SemacquireMutex(0xc000222a8c, 0xc003ffbe00, 0x0)
        /usr/lib/go-1.15/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/lib/go-1.15/src/sync/rwmutex.go:50
github.com/pion/webrtc/v3.(*DTLSTransport).getSRTCPSession(0xc000222a80, 0x2, 0x2, 0xc0035fba40)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/dtlstransport.go:225 +0x127
github.com/pion/webrtc/v3.(*PeerConnection).WriteRTCP(0xc0024b64e0, 0xc0052823e0, 0x2, 0x2, 0x2, 0xc0052823e0)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/peerconnection.go:1690 +0x8d
sfu/rtpconn.sendSR(0xc003e942a0, 0x0, 0x0)
        /home/jch/go/src/sfu/rtpconn/rtpconn.go:851 +0x705
sfu/rtpconn.rtcpDownSender(0xc003e942a0)
        /home/jch/go/src/sfu/rtpconn/rtpconn.go:857 +0x3c
created by sfu/rtpconn.addDownConnTracks
        /home/jch/go/src/sfu/rtpconn/webclient.go:573 +0x22b
```

```
goroutine 26850 [semacquire, 2 minutes]:
sync.runtime_SemacquireMutex(0xc000222a8c, 0x0, 0x0)
        /usr/lib/go-1.15/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/lib/go-1.15/src/sync/rwmutex.go:50
github.com/pion/webrtc/v3.(*DTLSTransport).State(0xc000222a80, 0x0)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/dtlstransport.go:114 +0xa5
github.com/pion/webrtc/v3.(*PeerConnection).createICETransport.func1(0x2)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/peerconnection.go:698 +0x6c
github.com/pion/webrtc/v3.(*ICETransport).onConnectionStateChange(0xc001f50200, 0x2)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/icetransport.go:207 +0x74
github.com/pion/webrtc/v3.(*ICETransport).Start.func1(0x2)
        /home/jch/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.0-beta.4/icetransport.go:95 +0x7f
github.com/pion/ice/v2.(*Agent).onConnectionStateChange(0xc0028d9340, 0x2)
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/agent.go:392 +0x64
github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func2(0xc0028d9340)
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/agent.go:418 +0x108
created by github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine
        /home/jch/go/pkg/mod/github.com/pion/ice/v2@v2.0.1/agent.go:408 +0x65
```

**Comment by Sean-Der** [comment]
@jech I think this was fixed with https://github.com/pion/webrtc/issues/1430 !

Mind double checking my work and comparing the stack traces to ensure I am not closing it incorrectly :)

**Comment by jech** [comment]
It does look similar, granted.  I won't be able to reproduce it, since I should no longer be vulnerable (I now defer closing PCs until after I've released all locks), so I guess I might as well close it.

Sean, are you planning to cut a release, or should I depend on a git hash?

**Comment by Sean-Der** [comment]
Tagged `v3.0.0-beta.5`!

I am hoping to start `new-media-api` branch this weekend. After that is merged we are gonna be in Alpha territory.  https://github.com/pion/webrtc/projects/18

**Comment by jech** [comment]
Thanks!  Updated and deployed.  Let's hope the next seminar doesn't
require any server restarts

> I am hoping to start new-media-api branch this weekend. After that is merged we
> are gonna be in Alpha territory.

Er... shouldn't beta come after alpha?  Won't the Go tools become confused
if you go backwards?
