### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc#1466]
This is a list of known flaky tests that need investigating. It is unknown if these are still even an issue. 

* [x] TestICERestart (Fixed by https://github.com/pion/ice/commit/302290a7846159720a0feaa9d0d696f62ee7b50f)
* [ ] TestPeerConnection_GetStats (on Windows)
* [ ] TestPeerConnection_Renegotiation_Trickle
* [ ] TestPeerConnection_Renegotiation_AddTrack_Rename
* [x] TestNegotiationNeededStressOneSided (Fixed by 29f8b446deeef0973d6cbbce66a1928de2af5bb6)

**Comment by tarrencev** [comment]
Trace for `TestSettingEngine_SetICETCP`:

```
=== RUN   TestSettingEngine_SetICETCP
    util.go:38: Unexpected routines on test startup: 
        goroutine 17475 [chan receive]:
        github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func1(0xc0000eb080)
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:405 +0x83
        created by github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:401 +0x4d
        
        goroutine 17474 [select]:
        github.com/pion/ice/v2.(*Agent).taskLoop(0xc0000eb080)
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:218 +0x24b
        created by github.com/pion/ice/v2.NewAgent
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:349 +0x11f7
        
        goroutine 17409 [IO wait]:
        internal/poll.runtime_pollWait(0x7f442c773e68, 0x72, 0x117d440)
        	/opt/hostedtoolcache/go/1.14.10/x64/src/runtime/netpoll.go:203 +0x55
        internal/poll.(*pollDesc).wait(0xc0002ae618, 0x72, 0x7f442c775900, 0x0, 0x0)
        	/opt/hostedtoolcache/go/1.14.10/x64/src/internal/poll/fd_poll_runtime.go:87 +0xe4
        internal/poll.(*pollDesc).waitRead(...)
        	/opt/hostedtoolcache/go/1.14.10/x64/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).RawRead(0xc0002ae600, 0xc000552000, 0x0, 0x0)
        	/opt/hostedtoolcache/go/1.14.10/x64/src/internal/poll/fd_unix.go:534 +0x17e
        net.(*rawConn).Read(0xc0000aa4e8, 0xc000552000, 0x1, 0x1)
        	/opt/hostedtoolcache/go/1.14.10/x64/src/net/rawconn.go:43 +0x6f
        golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc0000bca40, 0xc000291d70, 0x0, 0x0, 0x10)
        	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20201002202402-0a1ea396d57c/internal/socket/rawconn_msg.go:32 +0x3e2
        golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
        	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20201002202402-0a1ea396d57c/internal/socket/socket.go:247
        golang.org/x/net/ipv4.(*payloadHandler).ReadFrom(0xc0002b9050, 0xc000288000, 0x200, 0x200, 0xc0000f1a00, 0x5a80ac, 0x12ef2f0, 0x12ef350, 0xf, 0x16f85f3)
        	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20201002202402-0a1ea396d57c/ipv4/payload_cmsg.go:31 +0x211
        github.com/pion/mdns.(*Conn).start(0xc0002ae880)
        	/home/runner/go/pkg/mod/github.com/pion/mdns@v0.0.4/conn.go:256 +0x175
        created by github.com/pion/mdns.Server
        	/home/runner/go/pkg/mod/github.com/pion/mdns@v0.0.4/conn.go:98 +0x714
        
        goroutine 17476 [select]:
        github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func2(0xc0000eb080)
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:414 +0x15a
        created by github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine
        	/home/runner/go/pkg/mod/github.com/pion/ice/v2@v2.0.9/agent.go:412 +0x6f
```

**Comment by at-wat** [comment]
On WASM
```
=== RUN   TestNew
    peerconnection_test.go:80: 
        	Error Trace:	peerconnection_test.go:80
        	Error:      	Received unexpected error:
        	            	syscall/js: call of Value.Get on undefined
        	Test:       	TestNew
    peerconnection_test.go:81: 
        	Error Trace:	peerconnection_test.go:81
        	Error:      	Expected value not to be nil.
        	Test:       	TestNew
--- FAIL: TestNew (0.00s)
=== RUN   TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "valid": init failed: syscall/js: call of Value.Get on undefined
    peerconnection_test.go:203: SetConfiguration "valid": err = runtime error: invalid memory address or nil pointer dereference, want <nil>
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:132: 
        	Error Trace:	peerconnection_test.go:132
        	            				peerconnection_test.go:196
        	Error:      	Expected nil, but got: &js.ValueError{Method:"Value.Get", Type:0}
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:135: 
        	Error Trace:	peerconnection_test.go:135
        	            				peerconnection_test.go:196
        	Error:      	Expected nil, but got: "invalid memory address or nil pointer dereference"
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "closed connection": init failed: runtime error: invalid memory address or nil pointer dereference
    peerconnection_test.go:203: SetConfiguration "closed connection": err = runtime error: invalid memory address or nil pointer dereference, want InvalidStateError: connection closed
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "update PeerIdentity": init failed: syscall/js: call of Value.Get on undefined
    peerconnection_test.go:203: SetConfiguration "update PeerIdentity": err = runtime error: invalid memory address or nil pointer dereference, want InvalidModificationError: peerIdentity cannot be modified
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "update BundlePolicy": init failed: syscall/js: call of Value.Get on undefined
    peerconnection_test.go:203: SetConfiguration "update BundlePolicy": err = runtime error: invalid memory address or nil pointer dereference, want InvalidModificationError: bundle policy cannot be modified
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "update RTCPMuxPolicy": init failed: syscall/js: call of Value.Get on undefined
    peerconnection_test.go:203: SetConfiguration "update RTCPMuxPolicy": err = runtime error: invalid memory address or nil pointer dereference, want InvalidModificationError: rtcp mux policy cannot be modified
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
    peerconnection_test.go:198: SetConfiguration "update ICECandidatePoolSize": init failed: syscall/js: call of Value.Get on undefined
    peerconnection_test.go:203: SetConfiguration "update ICECandidatePoolSize": err = runtime error: invalid memory address or nil pointer dereference, want InvalidModificationError: ice candidate pool size cannot be modified
    peerconnection_test.go:206: 
        	Error Trace:	peerconnection_test.go:206
        	Error:      	Received unexpected error:
        	            	runtime error: invalid memory address or nil pointer dereference
        	Test:       	TestPeerConnection_SetConfiguration
--- FAIL: TestPeerConnection_SetConfiguration (0.01s)
=== RUN   TestPeerConnection_GetConfiguration
    peerconnection_test.go:212: 
        	Error Trace:	peerconnection_test.go:212
        	Error:      	Received unexpected error:
        	            	syscall/js: call of Value.Get on undefined
        	Test:       	TestPeerConnection_GetConfiguration
--- FAIL: TestPeerConnection_GetConfiguration (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x847d58 addr=0x23340010 pc=0x0]

goroutine 166 [running]:
testing.tRunner.func1.1(0x4d9a0, 0x3be5a0)
	/home/runner/go/src/testing/testing.go:1057 +0x1b
testing.tRunner.func1(0x8e2d80)
	/home/runner/go/src/testing/testing.go:1060 +0x35
panic(0x4d9a0, 0x3be5a0)
	/home/runner/go/src/runtime/panic.go:969 +0x13
github.com/pion/webrtc/v3.(*PeerConnection).GetConfiguration(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/webrtc/webrtc/peerconnection_js.go:234 +0x3
github.com/pion/webrtc/v3.TestPeerConnection_GetConfiguration(0x8e2d80)
	/home/runner/work/webrtc/webrtc/peerconnection_test.go:221 +0x4
testing.tRunner(0x8e2d80, 0xb5ca8)
	/home/runner/go/src/testing/testing.go:1108 +0xc
created by testing.(*T).Run
	/home/runner/go/src/testing/testing.go:1159 +0x30
FAIL	github.com/pion/webrtc/v3	7.753s
```

**Comment by Sean-Der** [comment]
We haven't had a failed build for master in 35 commits, so closing for now. I am sure more will arrive in the future but I feel good about where we are at today :)
