### ISSUE TITLE
example/rtp-forwarder panic

### ISSUE THREAD

**Issue by mango009** [pion/webrtc#2161]
Trying to run example/rtp-forwarder from the `master` branch.

env:
Mac OS 12.3
Go : `go version go1.18 darwin/amd64`

After hitting the **Start Session** button in **jsfiddle** `rtp-forwader panic:

```bash
Connection State has changed connected 
Ctrl+C the remote client to stop the demo
Peer Connection State has changed: connected
panic: <nil>

goroutine 59 [running]:
main.main.func3(0xc000216a20, 0xc000238290)
	/Users/mango/tools/webrtc/examples/rtp-forwarder/main.go:147 +0x3df
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
	/Users/mango/tools/webrtc/peerconnection.go:459 +0x17d
```

**Comment by mango009** [comment]
Unreproducible. Closing it.
