### ISSUE TITLE
Following your rtp forwarder example, getting nil pointer derefrence 

### ISSUE THREAD

**Issue by rlewkowicz** [pion/webrtc#2203]
go version
go version go1.17 linux/amd64

webrtc/examples/rtp-forwarder

```
export GO111MODULE=on
build .
# token stuff in fiddle
echo "$TOKEN" |  ./rtp-forwarder
# take response and put it in fiddle
Connection State has changed connected 
Ctrl+C the remote client to stop the demo
Peer Connection State has changed: connected
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7ac8d0]

goroutine 68 [running]:
main.main.func3(0xc0001a3e60, 0x3)
	/home/ryan/Repos/active/rtc/rtp/webrtc/examples/rtp-forwarder/main.go:166 +0x370
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
	/home/ryan/Repos/active/rtc/rtp/webrtc/peerconnection.go:459 +0x17d
```

**Comment by mengelbart** [comment]
Thanks for reporting! I think https://github.com/pion/webrtc/pull/2204 should fix this issue.
