### ISSUE TITLE
TestMulticastDNSCandidates fail probabilistically in local

### ISSUE THREAD

**Issue by zeek0x** [pion/webrtc#2625]
### Your environment.
  - Version: master HEAD eed2bb2d3b9f204f9de1cd7e1046ca5d652778d2
  - Browser: *include version*
  - Other Information
    - go version go1.21.4 darwin/amd64
    - macOS Ventura 13.4

### What did you do?

Run the following locally. It might take a few attempts before encountering a failure.

```console
go test -run MulticastDNSCandidates 
```

### What did you expect?

PASS

### What happened?

Fail: timeout

<details>

<summary>Failing log</summary>

```console
goroutine profile: total 33
10 @ 0x103db0e 0x1036cf7 0x106b3e5 0x10a59c7 0x10a79eb 0x10a79d9 0x1278d05 0x1295859 0x1293c50 0x1293dea 0x1448cea 0x10715e1
#       0x106b3e4       internal/poll.runtime_pollWait+0x84                     /usr/local/opt/go/libexec/src/runtime/netpoll.go:343
#       0x10a59c6       internal/poll.(*pollDesc).wait+0x26                     /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84
#       0x10a79ea       internal/poll.(*pollDesc).waitRead+0x22a                /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89
#       0x10a79d8       internal/poll.(*FD).ReadFromInet6+0x218                 /usr/local/opt/go/libexec/src/internal/poll/fd_unix.go:274
#       0x1278d04       net.(*netFD).readFromInet6+0x24                         /usr/local/opt/go/libexec/src/net/fd_posix.go:72
#       0x1295858       net.(*UDPConn).readFrom+0x78                            /usr/local/opt/go/libexec/src/net/udpsock_posix.go:59
#       0x1293c4f       net.(*UDPConn).readFromUDP+0x2f                         /usr/local/opt/go/libexec/src/net/udpsock.go:149
#       0x1293de9       net.(*UDPConn).ReadFrom+0x49                            /usr/local/opt/go/libexec/src/net/udpsock.go:158
#       0x1448ce9       github.com/pion/ice/v3.(*candidateBase).recvLoop+0x149  /path/to/pion/ice/candidate_base.go:228

4 @ 0x103db0e 0x1036cf7 0x106b3e5 0x10a59c7 0x10a766b 0x10a7659 0x1278c05 0x1295991 0x1293c50 0x1293dea 0x1448cea 0x10715e1
#       0x106b3e4       internal/poll.runtime_pollWait+0x84                     /usr/local/opt/go/libexec/src/runtime/netpoll.go:343
#       0x10a59c6       internal/poll.(*pollDesc).wait+0x26                     /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84
#       0x10a766a       internal/poll.(*pollDesc).waitRead+0x22a                /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89
#       0x10a7658       internal/poll.(*FD).ReadFromInet4+0x218                 /usr/local/opt/go/libexec/src/internal/poll/fd_unix.go:247
#       0x1278c04       net.(*netFD).readFromInet4+0x24                         /usr/local/opt/go/libexec/src/net/fd_posix.go:66
#       0x1295990       net.(*UDPConn).readFrom+0x1b0                           /usr/local/opt/go/libexec/src/net/udpsock_posix.go:52
#       0x1293c4f       net.(*UDPConn).readFromUDP+0x2f                         /usr/local/opt/go/libexec/src/net/udpsock.go:149
#       0x1293de9       net.(*UDPConn).ReadFrom+0x49                            /usr/local/opt/go/libexec/src/net/udpsock.go:158
#       0x1448ce9       github.com/pion/ice/v3.(*candidateBase).recvLoop+0x149  /path/to/pion/ice/candidate_base.go:228

2 @ 0x103db0e 0x100a48d 0x100a0b2 0x14472f7 0x10715e1
#       0x14472f6       github.com/pion/ice/v3.(*Agent).candidatePairRoutine+0x56       /path/to/pion/ice/agent_handlers.go:45

2 @ 0x103db0e 0x100a48d 0x100a0b2 0x1447369 0x10715e1
#       0x1447368       github.com/pion/ice/v3.(*Agent).connectionStateRoutine+0x48     /path/to/pion/ice/agent_handlers.go:51

2 @ 0x103db0e 0x100a48d 0x100a0b2 0x1447497 0x10715e1
#       0x1447496       github.com/pion/ice/v3.(*Agent).candidateRoutine+0x56   /path/to/pion/ice/agent_handlers.go:57

2 @ 0x103db0e 0x1036cf7 0x106b3e5 0x10a59c7 0x10abb2a 0x10abb13 0x128ddd6 0x132b4f2 0x1333dc9 0x1333db7 0x13c76e5 0x10715e1
#       0x106b3e4       internal/poll.runtime_pollWait+0x84                     /usr/local/opt/go/libexec/src/runtime/netpoll.go:343
#       0x10a59c6       internal/poll.(*pollDesc).wait+0x26                     /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84
#       0x10abb29       internal/poll.(*pollDesc).waitRead+0x129                /usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89
#       0x10abb12       internal/poll.(*FD).RawRead+0x112                       /usr/local/opt/go/libexec/src/internal/poll/fd_unix.go:708
#       0x128ddd5       net.(*rawConn).Read+0x35                                /usr/local/opt/go/libexec/src/net/rawconn.go:44
#       0x132b4f1       golang.org/x/net/internal/socket.(*Conn).recvMsg+0x151  /path/to/go/pkg/mod/golang.org/x/net@v0.17.0/internal/socket/rawconn_msg.go:28
#       0x1333dc8       golang.org/x/net/internal/socket.(*Conn).RecvMsg+0x228  /path/to/go/pkg/mod/golang.org/x/net@v0.17.0/internal/socket/socket.go:247
#       0x1333db6       golang.org/x/net/ipv4.(*payloadHandler).ReadFrom+0x216  /path/to/go/pkg/mod/golang.org/x/net@v0.17.0/ipv4/payload_cmsg.go:32
#       0x13c76e4       github.com/pion/mdns.(*Conn).start+0xe4                 /path/to/go/pkg/mod/github.com/pion/mdns@v0.0.9/conn.go:319

2 @ 0x103db0e 0x104df65 0x1107cd8 0x10715e1
#       0x1107cd7       context.(*cancelCtx).propagateCancel.func2+0x97 /usr/local/opt/go/libexec/src/context/context.go:505

2 @ 0x103db0e 0x104df65 0x143e8ee 0x10715e1
#       0x143e8ed       github.com/pion/ice/v3.(*Agent).taskLoop+0x12d  /path/to/pion/ice/agent.go:238

2 @ 0x103db0e 0x104df65 0x144043f 0x10715e1
#       0x144043e       github.com/pion/ice/v3.(*Agent).connectivityChecks+0x19e        /path/to/pion/ice/agent.go:481

1 @ 0x1033671 0x106b03d 0x11abe71 0x11abca5 0x11a8746 0x152ad5d 0x10715e1
#       0x106b03c       runtime/pprof.runtime_goroutineProfileWithLabels+0x1c                   /usr/local/opt/go/libexec/src/runtime/mprof.go:844
#       0x11abe70       runtime/pprof.writeRuntimeProfile+0xb0                                  /usr/local/opt/go/libexec/src/runtime/pprof/pprof.go:734
#       0x11abca4       runtime/pprof.writeGoroutine+0x44                                       /usr/local/opt/go/libexec/src/runtime/pprof/pprof.go:694
#       0x11a8745       runtime/pprof.(*Profile).WriteTo+0x145                                  /usr/local/opt/go/libexec/src/runtime/pprof/pprof.go:329
#       0x152ad5c       github.com/pion/webrtc/v4.TestMulticastDNSCandidates.TimeOut.func2+0x3c /path/to/go/pkg/mod/github.com/pion/transport/v3@v3.0.1/test/util.go:24

1 @ 0x103db0e 0x100a48d 0x100a092 0x1119788 0x111b89e 0x111895f 0x111b785 0x111a176 0x15352dc 0x103d69b 0x10715e1
#       0x1119787       testing.(*T).Run+0x3c7          /usr/local/opt/go/libexec/src/testing/testing.go:1649
#       0x111b89d       testing.runTests.func1+0x3d     /usr/local/opt/go/libexec/src/testing/testing.go:2054
#       0x111895e       testing.tRunner+0xfe            /usr/local/opt/go/libexec/src/testing/testing.go:1595
#       0x111b784       testing.runTests+0x444          /usr/local/opt/go/libexec/src/testing/testing.go:2052
#       0x111a175       testing.(*M).Run+0x635          /usr/local/opt/go/libexec/src/testing/testing.go:1925
#       0x15352db       main.main+0x19b                 _testmain.go:537
#       0x103d69a       runtime.main+0x2ba              /usr/local/opt/go/libexec/src/runtime/proc.go:267

1 @ 0x103db0e 0x100a48d 0x100a092 0x14e0cca 0x111895f 0x10715e1
#       0x14e0cc9       github.com/pion/webrtc/v4.TestMulticastDNSCandidates+0x2a9      /path/to/pion/webrtc/peerconnection_go_test.go:819
#       0x111895e       testing.tRunner+0xfe                                            /usr/local/opt/go/libexec/src/testing/testing.go:1595

1 @ 0x103db0e 0x104df65 0x1461328 0x148393b 0x14838fd 0x149dbc8 0x149541c 0x148c054 0x10715e1
#       0x1461327       github.com/pion/ice/v3.(*Agent).connect+0x167                                   /path/to/pion/ice/transport.go:59
#       0x148393a       github.com/pion/ice/v3.(*Agent).Accept+0x49a                                    /path/to/pion/ice/transport.go:26
#       0x14838fc       github.com/pion/webrtc/v4.(*ICETransport).Start+0x45c                           /path/to/pion/webrtc/icetransport.go:150
#       0x149dbc7       github.com/pion/webrtc/v4.(*PeerConnection).startTransports+0x127               /path/to/pion/webrtc/peerconnection.go:2276
#       0x149541b       github.com/pion/webrtc/v4.(*PeerConnection).SetRemoteDescription.func2+0x1fb    /path/to/pion/webrtc/peerconnection.go:1224
#       0x148c053       github.com/pion/webrtc/v4.(*operations).start+0x53                              /path/to/pion/webrtc/operations.go:93

1 @ 0x103db0e 0x104df65 0x1461328 0x14839d2 0x1483991 0x149dbc8 0x149541c 0x148c054 0x10715e1
#       0x1461327       github.com/pion/ice/v3.(*Agent).connect+0x167                                   /path/to/pion/ice/transport.go:59
#       0x14839d1       github.com/pion/ice/v3.(*Agent).Dial+0x531                                      /path/to/pion/ice/transport.go:20
#       0x1483990       github.com/pion/webrtc/v4.(*ICETransport).Start+0x4f0                           /path/to/pion/webrtc/icetransport.go:144
#       0x149dbc7       github.com/pion/webrtc/v4.(*PeerConnection).startTransports+0x127               /path/to/pion/webrtc/peerconnection.go:2276
#       0x149541b       github.com/pion/webrtc/v4.(*PeerConnection).SetRemoteDescription.func2+0x1fb    /path/to/pion/webrtc/peerconnection.go:1224
#       0x148c053       github.com/pion/webrtc/v4.(*operations).start+0x53                              /path/to/pion/webrtc/operations.go:93

panic: timeout

goroutine 162 [running]:
github.com/pion/webrtc/v4.TestMulticastDNSCandidates.TimeOut.func2()
        /path/to/go/pkg/mod/github.com/pion/transport/v3@v3.0.1/test/util.go:27 +0x8c
created by time.goFunc
        /usr/local/opt/go/libexec/src/time/sleep.go:176 +0x2d
exit status 2
FAIL    github.com/pion/webrtc/v4       30.168s
```

</details>

### trace the test

https://github.com/pion/webrtc/blob/5cf4168432699aa28dd38765d93c18878b51f8bc/peerconnection_go_test.go#L795

"MulticastDNSCandidates" generates "pcOffer" and "pcAnswer" in "MulticastNDNSMode" and tests whether "pcAnswer" can receive data channel messages. However, in case of failure, the test times out without "pcAnswer's onDataChannel" ever being called. 

https://github.com/pion/webrtc/blob/5cf4168432699aa28dd38765d93c18878b51f8bc/peerconnection_go_test.go#L811-L814

I traced where test stopped when it failed.

Test goroutine
- TestMulticastDNSCandidates
  - signalPair
    - signalPairWithModification 
      - pcOffer.SetRemoteDescription(*pcAnswer.LocalDescription()) 
        - pc.ops.Enqueue(func() { ... pc.startTransports ... }  // async

Agent goroutine
- pc.startTransports
  - pc.iceTransport.Start
    - agent.Dial
      - a.connect // a means agent 
        - case <-a.onConnected

https://github.com/pion/ice/blob/8d69e9ecd824967bb9aa0bba4c9f0fc7ae6949ee/transport.go#L55-L62

In the failure case, close(a.onConnected) was not called and execution stopped.
Therefore, I tracked the code path in the success case.

- close(a.onConnected)
  -  a.onConnectedOnce.Do(func()
    -  agent.setSelectedPair
      - controllingSelector.HandleSuccessResponse
        - agent.handleInbound
          - agent.handleInboundPacket
            - recvLoop

https://github.com/pion/ice/blob/8d69e9ecd824967bb9aa0bba4c9f0fc7ae6949ee/candidate_base.go#L226-L236

I found that in the recvLoop connection, net.UDPConn is utilized. Upon examining the transmission side, it appeared to be sending data.

So, the test may have probabilistically failed due to lost packets resulting from the use of a UDP connection.

Is there a good way to fix this test?

**Comment by enobufs** [comment]
I am seeing the exact same error on my MBP/M1.
```
% go version
go version go1.21.5 darwin/arm64
```

Occurrence is pretty high.. I'd say more than 75% with this command line:
```
% go test -v -p 1 -race -count 1 ./... -run TestMulticastDNSCandidates
```

pion/webrtc rev c259e89 (current master).  This occurs on the /v3 branch HEAD as well.

**Comment by enobufs** [comment]
From my manual binary search, this error began to occur from v3.2.18.  (It does not occur v3.2.17 and earlier)

**Comment by enobufs** [comment]
The exact commits that appear to be breaking the test case as reported here are:

* pion/mdns@608f20b
* pion/mdns@17c664e

These are included in pion/mdns v0.0.8.

**Comment by edaniels** [comment]
Will close when this makes it to this repo

**Comment by Sean-Der** [comment]
@edaniels and @enobufs this is amazing thank you so much for coding and reviewing this. I am totally underwater seeing this made my day :)

**Comment by edaniels** [comment]
@zeek0x if you still see issues, just reopen this!

**Comment by zeek0x** [comment]
The latest version no longer reproduces the error. Thanks for fixing it!
