### ISSUE TITLE
SampleBuilder causes segmentation fault

### ISSUE THREAD

**Issue by at-wat** [pion/webrtc#2740]
### Your environment.
  - Version: v4.0.0-beta.14 and later
  - Updating pion/webrtc v4.0.0-beta.13 to v4.0.0-beta.16 causes segmentation fault in an unit test of my product code

### What did you do?
Passing specific data to SampleBuilder and Flush.
Previously, v4.0.0-beta.13 passed the test.

Reproduction unit test:
```go
func TestSampleBuilder_Flush2(t *testing.T) {
  s := New(50, &codecs.VP8Packet{}, 10)

  s.Push(&rtp.Packet{
    Header: rtp.Header{
      Marker:         true,
      SequenceNumber: 0x3e8,
      Timestamp:      0x2710,
      SSRC:           0x1234,
    },
    Payload: []uint8{0x10, 0xd1, 0x3c, 0x1},
  })
  s.Push(&rtp.Packet{
    Header: rtp.Header{
      Marker:         false,
      SequenceNumber: 0x3e9,
      Timestamp:      0x276a,
      SSRC:           0x1234,
    }, 
    Payload: []uint8{0x10, 0xf0, 0xb1, 0x2, 0x9d, 0x1, 0x2a, 0x0, 0x5, 0xab, 0x1},
  })
  s.Push(&rtp.Packet{
    Header: rtp.Header{
      Marker:         true,
      SequenceNumber: 0x3ea,
      Timestamp:      0x276a,
      SSRC:           0x1234,                                      
    },
    Payload: []uint8{0x0, 0x2},
  })

  s.Flush()
}
```

### What did you expect?
No behavior change after updating SampleBuilder to v4.0.0-beta.14 and later.

### What happened?
v4.0.0-beta.14 and later causes segmentation fault.
```
=== RUN   TestSampleBuilder_Flush2
--- FAIL: TestSampleBuilder_Flush2 (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x530600]

goroutine 64 [running]:
testing.tRunner.func1.2({0x5ba6c0, 0x786f20})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x5ba6c0?, 0x786f20?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/pion/interceptor/pkg/jitterbuffer.(*PriorityQueue).Find(...)
	/home/at-wat/go/pkg/mod/github.com/pion/interceptor@v0.1.27/pkg/jitterbuffer/priority_queue.go:54
github.com/pion/interceptor/pkg/jitterbuffer.(*JitterBuffer).PeekAtSequence(0xc001f18000?, 0x9b9c?)
	/home/at-wat/go/pkg/mod/github.com/pion/interceptor@v0.1.27/pkg/jitterbuffer/jitter_buffer.go:221 +0xa0
github.com/pion/webrtc/v4/pkg/media/samplebuilder.(*SampleBuilder).buildSample(0xc001f18000, 0x1)
	/home/at-wat/go/src/github.com/pion/webrtc/pkg/media/samplebuilder/samplebuilder.go:225 +0x15d
github.com/pion/webrtc/v4/pkg/media/samplebuilder.(*SampleBuilder).purgeBuffers(0xc001f18000, 0x1)
	/home/at-wat/go/src/github.com/pion/webrtc/pkg/media/samplebuilder/samplebuilder.go:163 +0xfc
github.com/pion/webrtc/v4/pkg/media/samplebuilder.(*SampleBuilder).Flush(...)
	/home/at-wat/go/src/github.com/pion/webrtc/pkg/media/samplebuilder/samplebuilder.go:200
github.com/pion/webrtc/v4/pkg/media/samplebuilder.TestSampleBuilder_Flush2(0xc0000f6340?)
	/home/at-wat/go/src/github.com/pion/webrtc/pkg/media/samplebuilder/samplebuilder_test.go:603 +0x1ce
testing.tRunner(0xc0000f6340, 0x618530)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
FAIL	github.com/pion/webrtc/v4/pkg/media/samplebuilder	0.193s
FAIL
```

### References
- https://github.com/pion/webrtc/pull/2679 seems be related

**Comment by at-wat** [comment]
@thatsnotright @Sean-Der FYI

**Comment by Sean-Der** [comment]
@thatsnotright you have any available for this one? I can grab tonight otherwise

**Comment by Sean-Der** [comment]
@at-wat fixed! I tagged new versions of webrtc + interceptor, thanks for testing :)

**Comment by at-wat** [comment]
I confirmed the test in my product code works now!
