### ISSUE TITLE
TestDataChannel_Send occasionally fails

### ISSUE THREAD

**Issue by enobufs** [pion/webrtc#578]
### Your environment.
  - Version: e4e9088 (master)
  - Browser: n/a
  - Other Information - see below

### What did you do?
TestDataChannel_Send occasionally fails.

### What did you expect?
The test should pass.
The test use a data channel, send a "Ping" message from the offerrer, answerer receives it, then replies "Pong" back to the offerrer. When offerer receives "Pong", then the test completes.

### What happened?
When this happens, offerer sends "Ping" with no error, but **answerer never receives OnDataChannel() callback**.

Eventually, test.CheckRoutines(t) receives timeout, dumps the following error log.

```
$ go test -v -run TestDataChannel_Send
=== RUN   TestDataChannel_Send
--- FAIL: TestDataChannel_Send (20.22s)
    datachannel_test.go:22: closePair timed out waiting for done signal
    util.go:38: Unexpected routines:
        goroutine 8 [IO wait]:
        internal/poll.runtime_pollWait(0x1e55f08, 0x72, 0x0)
        	/Users/ytakeda/go/current/src/runtime/netpoll.go:182 +0x56
        internal/poll.(*pollDesc).wait(0xc00022ec98, 0x72, 0x2000, 0x2000, 0x0)
        	/Users/ytakeda/go/current/src/internal/poll/fd_poll_runtime.go:87 +0x9b
        internal/poll.(*pollDesc).waitRead(...)
        	/Users/ytakeda/go/current/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).ReadFrom(0xc00022ec80, 0xc000254000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go/current/src/internal/poll/fd_unix.go:219 +0x194
        net.(*netFD).readFrom(0xc00022ec80, 0xc000254000, 0x2000, 0x2000, 0x105acf0, 0xc000319eb8, 0x2, 0x2, 0xc000319eac)
        	/Users/ytakeda/go/current/src/net/fd_unix.go:208 +0x5b
        net.(*UDPConn).readFrom(0xc000010008, 0xc000254000, 0x2000, 0x2000, 0x1, 0x0, 0x0, 0xc0000961e0)
        	/Users/ytakeda/go/current/src/net/udpsock_posix.go:47 +0x6a
        net.(*UDPConn).ReadFrom(0xc000010008, 0xc000254000, 0x2000, 0x2000, 0x0, 0x0, 0xc000264000, 0x0, 0x0)
        	/Users/ytakeda/go/current/src/net/udpsock.go:121 +0x5e
        github.com/pions/ice.(*Candidate).recvLoop(0xc00024c000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/candidate.go:138 +0xf3
        created by github.com/pions/ice.(*Candidate).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/candidate.go:127 +0xe9

        goroutine 9 [select]:
        github.com/pions/ice.(*Agent).taskLoop(0xc0000ea120)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/agent.go:468 +0xde
        created by github.com/pions/ice.NewAgent
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/agent.go:180 +0x500

        goroutine 10 [IO wait]:
        internal/poll.runtime_pollWait(0x1e55e38, 0x72, 0x0)
        	/Users/ytakeda/go/current/src/runtime/netpoll.go:182 +0x56
        internal/poll.(*pollDesc).wait(0xc00022fc18, 0x72, 0x2000, 0x2000, 0x0)
        	/Users/ytakeda/go/current/src/internal/poll/fd_poll_runtime.go:87 +0x9b
        internal/poll.(*pollDesc).waitRead(...)
        	/Users/ytakeda/go/current/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).ReadFrom(0xc00022fc00, 0xc00027a000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go/current/src/internal/poll/fd_unix.go:219 +0x194
        net.(*netFD).readFrom(0xc00022fc00, 0xc00027a000, 0x2000, 0x2000, 0x105acf0, 0xc0002b5eb8, 0x2, 0x2, 0xc0002b5eac)
        	/Users/ytakeda/go/current/src/net/fd_unix.go:208 +0x5b
        net.(*UDPConn).readFrom(0xc000010030, 0xc00027a000, 0x2000, 0x2000, 0x1, 0x0, 0x0, 0xc0000c6840)
        	/Users/ytakeda/go/current/src/net/udpsock_posix.go:47 +0x6a
        net.(*UDPConn).ReadFrom(0xc000010030, 0xc00027a000, 0x2000, 0x2000, 0x0, 0x0, 0xc000020f00, 0x0, 0x0)
        	/Users/ytakeda/go/current/src/net/udpsock.go:121 +0x5e
        github.com/pions/ice.(*Candidate).recvLoop(0xc00024c160)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/candidate.go:138 +0xf3
        created by github.com/pions/ice.(*Candidate).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/candidate.go:127 +0xe9

        goroutine 11 [select]:
        github.com/pions/ice.(*Agent).taskLoop(0xc00024e120)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/agent.go:468 +0xde
        created by github.com/pions/ice.NewAgent
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/agent.go:180 +0x500

        goroutine 51 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0000e2550, 0xc0002ec000, 0x2000, 0x2000, 0x2000107, 0x0, 0xffffffffffffffff)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/ice.(*Conn).Read(0xc0002cc000, 0xc0002ec000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/transport.go:64 +0x94
        github.com/pions/webrtc/internal/mux.(*Mux).readLoop(0xc0002da190)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/mux.go:105 +0xb8
        created by github.com/pions/webrtc/internal/mux.NewMux
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/mux.go:43 +0x127

        goroutine 99 [sync.Cond.Wait]:
        runtime.goparkunlock(...)
        	/Users/ytakeda/go/current/src/runtime/proc.go:307
        sync.runtime_notifyListWait(0xc000278510, 0xc000000000)
        	/Users/ytakeda/go/current/src/runtime/sema.go:510 +0xf9
        sync.(*Cond).Wait(0xc000278500)
        	/Users/ytakeda/go/current/src/sync/cond.go:56 +0x9e
        github.com/pions/sctp.(*Stream).ReadSCTP(0xc00037e150, 0xc0004d8000, 0x4000, 0x4000, 0x1c00008, 0x0, 0x1, 0x1)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/stream.go:109 +0x127
        github.com/pions/datachannel.(*DataChannel).ReadDataChannel(0xc0002a0fc0, 0xc0004d8000, 0x4000, 0x4000, 0x10, 0xc0002b22a8, 0xc000001680, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:170 +0x6b
        github.com/pions/webrtc.(*DataChannel).readLoop(0xc0002500c0)
        	/Users/ytakeda/Projects/pions/webrtc/datachannel.go:262 +0x8a
        created by github.com/pions/webrtc.(*DataChannel).handleOpen
        	/Users/ytakeda/Projects/pions/webrtc/datachannel.go:255 +0xdc

        goroutine 67 [chan receive]:
        github.com/pions/srtp.(*SessionSRTCP).AcceptStream(0xc00049a780, 0xc00049a780, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session_srtcp.go:64 +0x48
        github.com/pions/webrtc.(*PeerConnection).drainSRTP(0xc000001680)
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1061 +0xa6
        created by github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription.func2
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:906 +0x420

        goroutine 54 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0002da1e0, 0xc00030e000, 0x2000, 0x2000, 0x1, 0x0, 0xc00033f680)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc0002d6050, 0xc00030e000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/endpoint.go:34 +0x4d
        github.com/pions/dtls.createConn.func1(0xc000302000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:135 +0xac
        created by github.com/pions/dtls.createConn
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:128 +0x3ab

        goroutine 38 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc000232910, 0xc00031c000, 0x2000, 0x2000, 0x4000105, 0x0, 0xffffffffffffffff)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/ice.(*Conn).Read(0xc0002c6008, 0xc00031c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/ice@v0.2.0/transport.go:64 +0x94
        github.com/pions/webrtc/internal/mux.(*Mux).readLoop(0xc0002d21e0)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/mux.go:105 +0xb8
        created by github.com/pions/webrtc/internal/mux.NewMux
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/mux.go:43 +0x127

        goroutine 42 [chan receive]:
        github.com/pions/srtp.(*SessionSRTP).AcceptStream(0xc0000bb1a0, 0xc0000bb1a0, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session_srtp.go:69 +0x48
        github.com/pions/webrtc.(*PeerConnection).drainSRTP.func1(0xc000086c00)
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1033 +0x84
        created by github.com/pions/webrtc.(*PeerConnection).drainSRTP
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1025 +0x43

        goroutine 41 [chan send]:
        github.com/pions/dtls.(*Conn).handleIncomingPacket(0xc000342000, 0xc000346000, 0x2d, 0x2000, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:382 +0x8bc
        github.com/pions/dtls.(*Conn).handleIncoming(0xc000342000, 0xc000346000, 0x45, 0x2000, 0x45, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:309 +0xac
        github.com/pions/dtls.createConn.func1(0xc000342000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:143 +0x146
        created by github.com/pions/dtls.createConn
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:128 +0x3ab

        goroutine 55 [chan receive]:
        github.com/pions/srtp.(*SessionSRTP).AcceptStream(0xc00049a5a0, 0xc00049a5a0, 0x0, 0x0, 0xc000469fc8)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session_srtp.go:69 +0x48
        github.com/pions/webrtc.(*PeerConnection).drainSRTP.func1(0xc000001680)
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1033 +0x84
        created by github.com/pions/webrtc.(*PeerConnection).drainSRTP
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1025 +0x43

        goroutine 68 [chan receive]:
        github.com/pions/dtls.(*Conn).Read(0xc000302000, 0xc0004e6000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/dtls@v1.2.2/conn.go:178 +0x4e
        github.com/pions/sctp.(*Association).readLoop(0xc0003661c0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:312 +0xa5
        created by github.com/pions/sctp.Client
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:160 +0x6f

        goroutine 23 [chan receive]:
        github.com/pions/srtp.(*SessionSRTCP).AcceptStream(0xc0000bb380, 0xc0000bb380, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session_srtcp.go:64 +0x48
        github.com/pions/webrtc.(*PeerConnection).drainSRTP(0xc000086c00)
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:1061 +0xa6
        created by github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription.func2
        	/Users/ytakeda/Projects/pions/webrtc/peerconnection.go:906 +0x420

        goroutine 56 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0002da230, 0xc000400000, 0x2000, 0x2000, 0x1458060, 0x1, 0xc000400000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc0002d6060, 0xc000400000, 0x2000, 0x2000, 0xc0002faf78, 0x13cbbec, 0xc000252000)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/endpoint.go:34 +0x4d
        github.com/pions/srtp.(*session).start.func1(0xc00049a5a0, 0xc0002d6440, 0x15ac220, 0xc00049a5a0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:120 +0xc0
        created by github.com/pions/srtp.(*session).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:107 +0x1e1

        goroutine 24 [chan send]:
        github.com/pions/sctp.(*Association).createStream(...)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:598
        github.com/pions/sctp.(*Association).getOrCreateStream(...)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:610
        github.com/pions/sctp.(*Association).handleData(0xc0001240e0, 0xc0004de000, 0x0, 0x0, 0x8a69a903)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:522 +0x82d
        github.com/pions/sctp.(*Association).handleChunk(0xc0001240e0, 0xc0002b7f40, 0x15ae4a0, 0xc0004de000, 0x0, 0x0, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:1149 +0x12ef
        github.com/pions/sctp.(*Association).handleInbound(0xc0001240e0, 0xc0004dc000, 0x2c, 0x2000, 0x2c, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:347 +0x1c4
        github.com/pions/sctp.(*Association).readLoop(0xc0001240e0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:317 +0xf1
        created by github.com/pions/sctp.Client
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:160 +0x6f

        goroutine 57 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0002da280, 0xc000404000, 0x2000, 0x2000, 0x1458060, 0xc0002f6f01, 0xc000404000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc0002d6070, 0xc000404000, 0x2000, 0x2000, 0xc000304240, 0x0, 0x1)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/endpoint.go:34 +0x4d
        github.com/pions/srtp.(*session).start.func1(0xc00049a780, 0xc0002d6450, 0x15ac1e0, 0xc00049a780)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:120 +0xc0
        created by github.com/pions/srtp.(*session).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:107 +0x1e1

        goroutine 43 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0002d2280, 0xc00040a000, 0x2000, 0x2000, 0x1458060, 0x1, 0xc00040a000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc0002c8070, 0xc00040a000, 0x2000, 0x2000, 0xc000462f78, 0x13cbbec, 0xc000252140)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/endpoint.go:34 +0x4d
        github.com/pions/srtp.(*session).start.func1(0xc0000bb1a0, 0xc0002c8cd0, 0x15ac220, 0xc0000bb1a0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:120 +0xc0
        created by github.com/pions/srtp.(*session).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:107 +0x1e1

        goroutine 44 [chan receive]:
        github.com/pions/transport/packetio.(*Buffer).Read(0xc0002d22d0, 0xc00040c000, 0x2000, 0x2000, 0x1458060, 0x1, 0xc00040c000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/transport@v0.5.0/packetio/buffer.go:135 +0x50
        github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc0002c8080, 0xc00040c000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        	/Users/ytakeda/Projects/pions/webrtc/internal/mux/endpoint.go:34 +0x4d
        github.com/pions/srtp.(*session).start.func1(0xc0000bb380, 0xc0002c8ce0, 0x15ac1e0, 0xc0000bb380)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:120 +0xc0
        created by github.com/pions/srtp.(*session).start
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/srtp@v1.1.2/session.go:107 +0x1e1

        goroutine 45 [chan receive]:
        github.com/pions/sctp.(*Association).AcceptStream(...)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:579
        github.com/pions/datachannel.Accept(0xc0003661c0, 0x1, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:111 +0x4a
        github.com/pions/webrtc.(*SCTPTransport).acceptDataChannels(0xc00049c8a0)
        	/Users/ytakeda/Projects/pions/webrtc/sctptransport.go:133 +0xb0
        created by github.com/pions/webrtc.(*SCTPTransport).Start
        	/Users/ytakeda/Projects/pions/webrtc/sctptransport.go:96 +0xee

        goroutine 26 [semacquire]:
        sync.runtime_SemacquireMutex(0xc0001240e4, 0x1066700)
        	/Users/ytakeda/go/current/src/runtime/sema.go:71 +0x3d
        sync.(*Mutex).Lock(0xc0001240e0)
        	/Users/ytakeda/go/current/src/sync/mutex.go:134 +0x109
        sync.(*RWMutex).Lock(0xc0001240e0)
        	/Users/ytakeda/go/current/src/sync/rwmutex.go:93 +0x2d
        github.com/pions/sctp.(*Association).sendPayloadData(0xc0001240e0, 0xc0004e4000, 0x1, 0x1, 0xc000000032, 0xc0004e4000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/association.go:910 +0x31
        github.com/pions/sctp.(*Stream).WriteSCTP(0xc000231110, 0xc0004d5e24, 0x4, 0x4, 0xc000000032, 0x20, 0x2000, 0xc0002fb648)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/stream.go:168 +0x10f
        github.com/pions/datachannel.(*DataChannel).writeDataChannelAck(0xc0004ce000, 0xc0002fb6c8, 0xc0004ce000)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:265 +0x65
        github.com/pions/datachannel.Server(0xc000231110, 0xc000000035, 0x1, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:153 +0x1a0
        github.com/pions/datachannel.Accept(0xc0001240e0, 0xc0000a69b0, 0x13881388, 0xc0000a69b0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:118 +0x87
        github.com/pions/webrtc.(*SCTPTransport).acceptDataChannels(0xc00049c5a0)
        	/Users/ytakeda/Projects/pions/webrtc/sctptransport.go:133 +0xb0
        created by github.com/pions/webrtc.(*SCTPTransport).Start
        	/Users/ytakeda/Projects/pions/webrtc/sctptransport.go:96 +0xee

        goroutine 58 [sync.Cond.Wait]:
        runtime.goparkunlock(...)
        	/Users/ytakeda/go/current/src/runtime/proc.go:307
        sync.runtime_notifyListWait(0xc0002ce910, 0xc000000000)
        	/Users/ytakeda/go/current/src/runtime/sema.go:510 +0xf9
        sync.(*Cond).Wait(0xc0002ce900)
        	/Users/ytakeda/go/current/src/sync/cond.go:56 +0x9e
        github.com/pions/sctp.(*Stream).ReadSCTP(0xc0003ce1c0, 0xc0004ae000, 0x4000, 0x4000, 0x1c00008, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/sctp@v1.4.3/stream.go:109 +0x127
        github.com/pions/datachannel.(*DataChannel).ReadDataChannel(0xc0002eeda0, 0xc0004ae000, 0x4000, 0x4000, 0x0, 0x0, 0x0, 0x0)
        	/Users/ytakeda/go_ws/pkg/mod/github.com/pions/datachannel@v1.2.1/datachannel.go:170 +0x6b
        github.com/pions/webrtc.(*DataChannel).readLoop(0xc000250180)
        	/Users/ytakeda/Projects/pions/webrtc/datachannel.go:262 +0x8a
        created by github.com/pions/webrtc.(*DataChannel).handleOpen
        	/Users/ytakeda/Projects/pions/webrtc/datachannel.go:255 +0xdc
FAIL
exit status 1
FAIL	github.com/pions/webrtc	20.288s
```

**Comment by enobufs** [comment]
Note: There are many similar tests in the sctp package, but I have not seen "accepting side" stalling...

**Comment by Sean-Der** [comment]
Tracking with https://github.com/pion/webrtc/issues/642
