### ISSUE TITLE
"closePair timed out" & "Unexpected routines" in datachannel test

### ISSUE THREAD

**Issue by maxhawkins** [pion/webrtc#612]
### Your environment.
  - Version: 7f6c01d5bc8dfcb6f0aaa70d12c02d8049a3fb7b

### What did you do?
Ran the tests on CI

### What happened?
Unexpected goroutine found in `TestDataChannelBufferedAmount/set_after_datachannel_becomes_open` test.

```
    --- FAIL: TestDataChannelBufferedAmount/set_after_datachannel_becomes_open (20.21s)
        datachannel_test.go:21: closePair timed out waiting for done signal
        util.go:38: Unexpected routines: 
            goroutine 153 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc0000cc640, 0xc00047a000, 0x2000, 0x2000, 0xc00025c120, 0xc0000e03f0, 0xc0000e03f0)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/ice.(*Conn).Read(0xc0000a44f8, 0xc00047a000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/transport.go:64 +0x107
            github.com/pion/webrtc/v2/internal/mux.(*Mux).readLoop(0xc0000cda90)
            	/home/travis/build/pion/webrtc/internal/mux/mux.go:105 +0x187
            created by github.com/pion/webrtc/v2/internal/mux.NewMux
            	/home/travis/build/pion/webrtc/internal/mux/mux.go:43 +0x235
            
            goroutine 151 [semacquire]:
            sync.runtime_SemacquireMutex(0xc0000d70e4, 0x900000000)
            	/home/travis/go/src/runtime/sema.go:71 +0x3d
            sync.(*Mutex).Lock(0xc0000d70e0)
            	/home/travis/go/src/sync/mutex.go:134 +0x149
            sync.(*RWMutex).Lock(0xc0000d70e0)
            	/home/travis/go/src/sync/rwmutex.go:93 +0x4a
            github.com/pion/sctp.(*Association).sendInit(0xc0000d70e0, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:282 +0x2a1
            github.com/pion/sctp.(*Association).init(0xc0000d70e0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:254 +0x412
            github.com/pion/sctp.Client(0xc9c000, 0xc0000db440, 0xc8bf60, 0xc0002aa060, 0xc00048ae08, 0x490b52, 0xc000088f00)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:184 +0xad
            github.com/pion/webrtc/v2.(*SCTPTransport).Start(0xc0000e2cb0, 0x0, 0x0, 0x0)
            	/home/travis/build/pion/webrtc/sctptransport.go:92 +0x1bb
            github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription.func2(0xc000000001, 0xc000088f00, 0xc00002986a, 0x10, 0xc00002d598, 0x20, 0xc00003090c, 0x7, 0xc000030914, 0x5f)
            	/home/travis/build/pion/webrtc/peerconnection.go:1027 +0x758
            created by github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription
            	/home/travis/build/pion/webrtc/peerconnection.go:970 +0x169e
            
            goroutine 155 [chan send]:
            github.com/pion/dtls.(*Conn).handleIncomingPacket(0xc0000db440, 0xc00047c000, 0x3d, 0x2000, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:387 +0x8c6
            github.com/pion/dtls.(*Conn).handleIncoming(0xc0000db440, 0xc00047c000, 0x55, 0x2000, 0x55, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:314 +0xd9
            github.com/pion/dtls.createConn.func1(0xc0000db440)
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:146 +0x175
            created by github.com/pion/dtls.createConn
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:131 +0x922
            
            goroutine 127 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc00047e190, 0xc000298000, 0x2000, 0x2000, 0xc000264f20, 0x46d3ec, 0x2000)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/webrtc/v2/internal/mux.(*Endpoint).Read(0xc00003f4b0, 0xc000298000, 0x2000, 0x2000, 0x0, 0xc00003e0a0, 0xc000264f90)
            	/home/travis/build/pion/webrtc/internal/mux/endpoint.go:34 +0x8b
            github.com/pion/srtp.(*session).start.func1(0xc00027a1c0, 0xc0001151b0, 0xc95d40, 0xc00027a1c0)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:124 +0xe6
            created by github.com/pion/srtp.(*session).start
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:111 +0x334
            
            goroutine 128 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc00047e1e0, 0xc00029a000, 0x2000, 0x2000, 0xc000054f20, 0x46d3ec, 0x2000)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/webrtc/v2/internal/mux.(*Endpoint).Read(0xc00003f4c0, 0xc00029a000, 0x2000, 0x2000, 0x0, 0xc00003e840, 0xc000054f90)
            	/home/travis/build/pion/webrtc/internal/mux/endpoint.go:34 +0x8b
            github.com/pion/srtp.(*session).start.func1(0xc00027a230, 0xc000115210, 0xc95d00, 0xc00027a230)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:124 +0xe6
            created by github.com/pion/srtp.(*session).start
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:111 +0x334
            
            goroutine 126 [chan receive]:
            github.com/pion/srtp.(*SessionSRTP).AcceptStream(0xc00027a1c0, 0xc000000001, 0x5, 0x0, 0xc0000a6f60)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session_srtp.go:81 +0x7e
            github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP.func1(0xc000089500)
            	/home/travis/build/pion/webrtc/peerconnection.go:1190 +0x12e
            created by github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP
            	/home/travis/build/pion/webrtc/peerconnection.go:1182 +0x6c
            
            goroutine 164 [chan send]:
            github.com/pion/sctp.(*Association).handleChunk(0xc0000d70e0, 0xc000275f38, 0xc97e00, 0xc0004b2f00, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:1625 +0x721
            github.com/pion/sctp.(*Association).handleInbound(0xc0000d70e0, 0xc0002de000, 0x30, 0x2000, 0x30, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:387 +0x246
            github.com/pion/sctp.(*Association).readLoop(0xc0000d70e0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:357 +0x131
            created by github.com/pion/sctp.Client
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:183 +0x9f
            
            goroutine 142 [IO wait]:
            internal/poll.runtime_pollWait(0x7f46678d7650, 0x72, 0x0)
            	/home/travis/go/src/runtime/netpoll.go:182 +0x56
            internal/poll.(*pollDesc).wait(0xc00021e418, 0x72, 0x2000, 0x2000, 0x0)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:87 +0xe5
            internal/poll.(*pollDesc).waitRead(...)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:92
            internal/poll.(*FD).ReadFrom(0xc00021e400, 0xc00011c000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/go/src/internal/poll/fd_unix.go:219 +0x232
            net.(*netFD).readFrom(0xc00021e400, 0xc00011c000, 0x2000, 0x2000, 0x42e5ed, 0xc000088600, 0x3, 0x42e350, 0x0)
            	/home/travis/go/src/net/fd_unix.go:208 +0x7a
            net.(*UDPConn).readFrom(0xc0000a40c0, 0xc00011c000, 0x2000, 0x2000, 0xc0004be2e0, 0x0, 0x0, 0x1)
            	/home/travis/go/src/net/udpsock_posix.go:47 +0x8e
            net.(*UDPConn).ReadFrom(0xc0000a40c0, 0xc00011c000, 0x2000, 0x2000, 0x55, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/go/src/net/udpsock.go:121 +0x96
            github.com/pion/ice.(*Candidate).recvLoop(0xc0000ba2c0)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:138 +0x164
            created by github.com/pion/ice.(*Candidate).start
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:127 +0x172
            
            goroutine 159 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc00047e140, 0xc0004b6000, 0x2000, 0x2000, 0x71, 0x487d2c, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/webrtc/v2/internal/mux.(*Endpoint).Read(0xc00003f4a0, 0xc0004b6000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
            	/home/travis/build/pion/webrtc/internal/mux/endpoint.go:34 +0x8b
            github.com/pion/dtls.createConn.func1(0xc0000db680)
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:138 +0xcc
            created by github.com/pion/dtls.createConn
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:131 +0x922
            
            goroutine 163 [chan receive]:
            github.com/pion/srtp.(*SessionSRTCP).AcceptStream(0xc00027a310, 0xc000000001, 0x6, 0x0, 0xc0000a7320)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session_srtcp.go:74 +0x7e
            github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP(0xc000088f00)
            	/home/travis/build/pion/webrtc/peerconnection.go:1218 +0x16b
            created by github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription.func2
            	/home/travis/build/pion/webrtc/peerconnection.go:1024 +0x720
            
            goroutine 144 [IO wait]:
            internal/poll.runtime_pollWait(0x7f46678d7580, 0x72, 0x0)
            	/home/travis/go/src/runtime/netpoll.go:182 +0x56
            internal/poll.(*pollDesc).wait(0xc00021e798, 0x72, 0x2000, 0x2000, 0x0)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:87 +0xe5
            internal/poll.(*pollDesc).waitRead(...)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:92
            internal/poll.(*FD).ReadFrom(0xc00021e780, 0xc0004a0000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/go/src/internal/poll/fd_unix.go:219 +0x232
            net.(*netFD).readFrom(0xc00021e780, 0xc0004a0000, 0x2000, 0x2000, 0xc000001d08, 0xc000001db8, 0xc000062e68, 0xc000062dc8, 0x7439c5)
            	/home/travis/go/src/net/fd_unix.go:208 +0x7a
            net.(*UDPConn).readFrom(0xc0000a40f8, 0xc0004a0000, 0x2000, 0x2000, 0xc00025cfc0, 0x7f4667a25008, 0xc000034ae0, 0xc000034c00)
            	/home/travis/go/src/net/udpsock_posix.go:47 +0x8e
            net.(*UDPConn).ReadFrom(0xc0000a40f8, 0xc0004a0000, 0x2000, 0x2000, 0x0, 0x0, 0xc00025ce70, 0x0, 0x0)
            	/home/travis/go/src/net/udpsock.go:121 +0x96
            github.com/pion/ice.(*Candidate).recvLoop(0xc0000ba580)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:138 +0x164
            created by github.com/pion/ice.(*Candidate).start
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:127 +0x172
            
            goroutine 129 [chan receive]:
            github.com/pion/srtp.(*SessionSRTP).AcceptStream(0xc00027a2a0, 0xc000000001, 0x6, 0x0, 0x1)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session_srtp.go:81 +0x7e
            github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP.func1(0xc000088f00)
            	/home/travis/build/pion/webrtc/peerconnection.go:1190 +0x12e
            created by github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP
            	/home/travis/build/pion/webrtc/peerconnection.go:1182 +0x6c
            
            goroutine 157 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc0000ccdc0, 0xc0004b4000, 0x2000, 0x2000, 0xc00025c600, 0xc0000e0480, 0xc0000e0480)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/ice.(*Conn).Read(0xc0000a4530, 0xc0004b4000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/transport.go:64 +0x107
            github.com/pion/webrtc/v2/internal/mux.(*Mux).readLoop(0xc00047e0f0)
            	/home/travis/build/pion/webrtc/internal/mux/mux.go:105 +0x187
            created by github.com/pion/webrtc/v2/internal/mux.NewMux
            	/home/travis/build/pion/webrtc/internal/mux/mux.go:43 +0x235
            
            goroutine 178 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc0000cdb30, 0xc0002a6000, 0x2000, 0x2000, 0xc000471720, 0x46d3ec, 0x2000)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/webrtc/v2/internal/mux.(*Endpoint).Read(0xc00003f2b0, 0xc0002a6000, 0x2000, 0x2000, 0x0, 0xc8bea0, 0x487ce2)
            	/home/travis/build/pion/webrtc/internal/mux/endpoint.go:34 +0x8b
            github.com/pion/srtp.(*session).start.func1(0xc00027a2a0, 0xc000115280, 0xc95d40, 0xc00027a2a0)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:124 +0xe6
            created by github.com/pion/srtp.(*session).start
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:111 +0x334
            
            goroutine 145 [IO wait]:
            internal/poll.runtime_pollWait(0x7f46678d74b0, 0x72, 0x0)
            	/home/travis/go/src/runtime/netpoll.go:182 +0x56
            internal/poll.(*pollDesc).wait(0xc00021e818, 0x72, 0x2000, 0x2000, 0x0)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:87 +0xe5
            internal/poll.(*pollDesc).waitRead(...)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:92
            internal/poll.(*FD).ReadFrom(0xc00021e800, 0xc0004a4000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/go/src/internal/poll/fd_unix.go:219 +0x232
            net.(*netFD).readFrom(0xc00021e800, 0xc0004a4000, 0x2000, 0x2000, 0x0, 0x203000, 0xc000065e68, 0x483a90, 0xc000065e40)
            	/home/travis/go/src/net/fd_unix.go:208 +0x7a
            net.(*UDPConn).readFrom(0xc0000a4338, 0xc0004a4000, 0x2000, 0x2000, 0xc000020300, 0x7f4667a256d0, 0xc000034ae0, 0xc000034c00)
            	/home/travis/go/src/net/udpsock_posix.go:47 +0x8e
            net.(*UDPConn).ReadFrom(0xc0000a4338, 0xc0004a4000, 0x2000, 0x2000, 0x0, 0x0, 0xc000020240, 0x0, 0x0)
            	/home/travis/go/src/net/udpsock.go:121 +0x96
            github.com/pion/ice.(*Candidate).recvLoop(0xc0000ba630)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:138 +0x164
            created by github.com/pion/ice.(*Candidate).start
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:127 +0x172
            
            goroutine 180 [select]:
            github.com/pion/sctp.(*rtxTimer).start.func1(0x40a7700000000000, 0xc0002e0018, 0xc00047f1d0, 0xc0002e20c0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/rtx_timer.go:150 +0x170
            created by github.com/pion/sctp.(*rtxTimer).start
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/rtx_timer.go:143 +0x14c
            
            goroutine 160 [chan receive]:
            github.com/pion/srtp.(*SessionSRTCP).AcceptStream(0xc00027a230, 0xc000000001, 0x5, 0x0, 0x1)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session_srtcp.go:74 +0x7e
            github.com/pion/webrtc/v2.(*PeerConnection).drainSRTP(0xc000089500)
            	/home/travis/build/pion/webrtc/peerconnection.go:1218 +0x16b
            created by github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription.func2
            	/home/travis/build/pion/webrtc/peerconnection.go:1024 +0x720
            
            goroutine 161 [chan receive]:
            github.com/pion/dtls.(*Conn).Read(0xc0000db680, 0xc0002e4000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
            	/home/travis/gopath/pkg/mod/github.com/pion/dtls@v1.3.2/conn.go:181 +0x87
            github.com/pion/sctp.(*Association).readLoop(0xc0000d6fc0)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:351 +0xde
            created by github.com/pion/sctp.Client
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:183 +0x9f
            
            goroutine 179 [chan receive]:
            github.com/pion/transport/packetio.(*Buffer).Read(0xc0000cdb80, 0xc0002a4000, 0x2000, 0x2000, 0xc000471f20, 0x46d3ec, 0x2000)
            	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.6.0/packetio/buffer.go:135 +0x99
            github.com/pion/webrtc/v2/internal/mux.(*Endpoint).Read(0xc00003f2c0, 0xc0002a4000, 0x2000, 0x2000, 0xa50f68, 0xc0000cee60, 0xc0002bd440)
            	/home/travis/build/pion/webrtc/internal/mux/endpoint.go:34 +0x8b
            github.com/pion/srtp.(*session).start.func1(0xc00027a310, 0xc0001152e0, 0xc95d00, 0xc00027a310)
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:124 +0xe6
            created by github.com/pion/srtp.(*session).start
            	/home/travis/gopath/pkg/mod/github.com/pion/srtp@v1.2.1/session.go:111 +0x334
            
            goroutine 146 [select]:
            github.com/pion/ice.(*Agent).taskLoop(0xc0000d6360)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/agent.go:468 +0x18a
            created by github.com/pion/ice.NewAgent
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/agent.go:180 +0x9f4
            
            goroutine 141 [IO wait]:
            internal/poll.runtime_pollWait(0x7f46678d7720, 0x72, 0x0)
            	/home/travis/go/src/runtime/netpoll.go:182 +0x56
            internal/poll.(*pollDesc).wait(0xc00021e398, 0x72, 0x2000, 0x2000, 0x0)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:87 +0xe5
            internal/poll.(*pollDesc).waitRead(...)
            	/home/travis/go/src/internal/poll/fd_poll_runtime.go:92
            internal/poll.(*FD).ReadFrom(0xc00021e380, 0xc00011a000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
            	/home/travis/go/src/internal/poll/fd_unix.go:219 +0x232
            net.(*netFD).readFrom(0xc00021e380, 0xc00011a000, 0x2000, 0x2000, 0x0, 0x203000, 0xc000061e68, 0x483a90, 0xc000061e40)
            	/home/travis/go/src/net/fd_unix.go:208 +0x7a
            net.(*UDPConn).readFrom(0xc0000a40a8, 0xc00011a000, 0x2000, 0x2000, 0xc000477560, 0x7f4667a256d0, 0xc0000348a0, 0xc0000349c0)
            	/home/travis/go/src/net/udpsock_posix.go:47 +0x8e
            net.(*UDPConn).ReadFrom(0xc0000a40a8, 0xc00011a000, 0x2000, 0x2000, 0x0, 0x0, 0xc0004774a0, 0x0, 0x0)
            	/home/travis/go/src/net/udpsock.go:121 +0x96
            github.com/pion/ice.(*Candidate).recvLoop(0xc0000ba210)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:138 +0x164
            created by github.com/pion/ice.(*Candidate).start
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/candidate.go:127 +0x172
            
            goroutine 150 [select]:
            github.com/pion/sctp.Client(0xc9c000, 0xc0000db680, 0xc8bf60, 0xc0002aa1c0, 0xc00048ee08, 0x490b52, 0xc000089500)
            	/home/travis/gopath/pkg/mod/github.com/pion/sctp@v1.5.0/association.go:186 +0x1aa
            github.com/pion/webrtc/v2.(*SCTPTransport).Start(0xc0000e2620, 0x0, 0x0, 0x0)
            	/home/travis/build/pion/webrtc/sctptransport.go:92 +0x1bb
            github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription.func2(0xc000000000, 0xc000089500, 0xc00002946a, 0x10, 0xc00002ced8, 0x20, 0xc00003060c, 0x7, 0xc000030614, 0x5f)
            	/home/travis/build/pion/webrtc/peerconnection.go:1027 +0x758
            created by github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription
            	/home/travis/build/pion/webrtc/peerconnection.go:970 +0x169e
            
            goroutine 143 [select]:
            github.com/pion/ice.(*Agent).taskLoop(0xc0000d6120)
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/agent.go:468 +0x18a
            created by github.com/pion/ice.NewAgent
            	/home/travis/gopath/pkg/mod/github.com/pion/ice@v0.2.1/agent.go:180 +0x9f4
```

**Comment by Sean-Der** [comment]
Tracking with https://github.com/pion/webrtc/issues/642
